package com.rarnu.tools.root.common;

public class FragmentNameConst {
    public static final String FN_INDEX = "index";
    public static final String FN_FEEDBACK = "feedback";
    public static final String FN_ABOUT = "about";
    public static final String FN_SYSTEM_COMPONENT = "systemcomponent";
    public static final String FN_SYSAPP = "sysapp";
    public static final String FN_SYSAPP_DETAIL = "sysappdetail";
    public static final String FN_SYSAPP_SELECTAPK = "sysappselectapk";
    public static final String FN_SETTINGS = "settings";
    public static final String FN_CLEAN_CACHE = "cleancache";
    public static final String FN_ENABLEAPP = "enableapp";
    public static final String FN_HTCROM = "htcrom";
    public static final String FN_COMP = "comp";
    public static final String FN_COMP_PACKAGE_INFO = "comppackageinfo";
    public static final String FN_MEM = "mem";
    public static final String FN_MEM_PROCESS = "memprocess";
    public static final String FN_HOST = "host";
    public static final String FN_HOST_ADD = "hostadd";
    public static final String FN_MEM_IGNORE = "memignore";
    public static final String FN_HOST_EDIT = "hostedit";
    public static final String FN_HOST_DEPRECATED = "hostdeprecated";
    public static final String FN_RECOMMAND = "recommand";
    public static final String FN_DATAAPP_REPORT = "dataappreport";
    public static final String FN_BACKUP = "backup";
    public static final String FN_RESTORE = "restore";
    public static final String FN_CUSTOM_CLEAN = "customclean";
    public static final String FN_TERMINAL = "terminal";
    public static final String FN_HARD_UPDATE = "hardupdate";
    public static final String FN_DISKINFO = "diskinfo";
    public static final String FN_FILESYSTEM = "filesystem";
    public static final String FN_POOL = "pool";
    public static final String FN_TEXT_EDITOR = "texteditor";
    public static final String FN_INSTALL_APK = "installapk";
    public static final String FN_BATCH_APPS = "batchapps";
    public static final String FN_BATCH_INSTALL = "batchinstall";
    public static final String FN_BATCH_UNINSTALL = "batchuninstall";
    public static final String FN_FIREWALL = "firewall";
    public static final String FN_BUILD_TEAM = "buildteam";
    public static final String FN_SHARE = "share";
    public static final String FN_GOOGLE = "google";
    public static final String FN_REMAINED_FILES = "remainedfiles";
}
