SEARCH_DIR(/usr/local/codetyphon/binLibraries/android-5.0-api21-arm/)
SEARCH_DIR(/usr/lib/x86_64-linux-gnu/)
SEARCH_DIR(./)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/imagemagick/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fcl-base/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/utmp/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/gnome1/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/openssl/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/mad/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fcl-async/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/modplug/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/httpd24/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/libtar/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fpmkunit/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fcl-image/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/sqlite/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/libxml2/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/iconvenc/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/uuid/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fftw/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fcl-registry/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fcl-fpcunit/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fcl-js/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/ncurses/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/oggvorbis/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fcl-db/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fcl-xml/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/oracle/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/hermes/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fcl-sound/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl-objpas/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/dbus/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/ibase/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/aspell/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/users/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl-extra/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/postgres/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fcl-res/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fcl-passrc/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fastcgi/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/bfd/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/zorba/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/ggi/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fcl-sdo/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/imlib/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/gtk1/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/lua/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fcl-process/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/svgalib/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/tcl/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/a52/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/hash/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/odbc/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/dblib/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fcl-pdf/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fcl-json/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/zlib/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/syslog/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/pasjpeg/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fcl-stl/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/unzip/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/mysql/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/openal/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/libpng/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/symbolic/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/paszlib/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/opengles/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/proj4/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/x11/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/opengl/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/fpgtk/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/libsee/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/newt/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/numlib/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/libenet/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/chm/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/gdbm/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/pcap/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/libcurl/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/libgd/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/httpd22/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/gmp/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/ldap/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/regexpr/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/libmicrohttpd/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/dts/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/units/arm-android/)
SEARCH_DIR(/usr/local/codetyphon/fpc/fpc64/bin/x86_64-linux/)
VERSION
{
  {
    global:
      Java_com_rarnu_tools_neo_api_NativeAPI_freezeComponents;
      Java_com_rarnu_tools_neo_api_NativeAPI_freezeComponent;
      Java_com_rarnu_tools_neo_api_NativeAPI_freezeApplication;
    local:
      *;
  };
}
INPUT(
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/dllprt0.o
/usr/local/codetyphon/binLibraries/android-5.0-api21-arm/crtbegin_so.o
/home/conquer/Documents/code/root-tools/native/lib/arm-android/cmd.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/system.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/lineinfo.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/exeinfo.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/strings.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/objpas.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/cthreads.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/classes.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/sysutils.o
/home/conquer/Documents/code/root-tools/native/lib/arm-android/jni2.o
/home/conquer/Documents/code/root-tools/native/lib/arm-android/jni_utils.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/math.o
/home/conquer/Documents/code/root-tools/native/lib/arm-android/unt_ljava.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/baseunix.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/unix.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/unixtype.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/initc.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/unixutil.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/ctypes.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/types.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/typinfo.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/rtlconsts.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/errors.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/sysconst.o
/home/conquer/Documents/code/root-tools/native/lib/arm-android/unt_cmd.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl-objpas/strutils.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/fcl-process/process.o
/home/conquer/Documents/code/root-tools/native/lib/arm-android/android.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/fcl-process/pipes.o
/usr/local/codetyphon/fpc/fpc64/units/arm-android/rtl/termio.o
)
INPUT(
-lc
-llog
)
GROUP(
-lc
)
INPUT(
/usr/local/codetyphon/binLibraries/android-5.0-api21-arm/crtend_so.o
)
SECTIONS
{
  .data           :
  {
    KEEP (*(.fpc .fpc.n_version .fpc.n_links))
  }
}
INSERT BEFORE .data1
