-arch
i386
-macosx_version_min
10.4
-L/usr/lib/
-L/System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/
-L/opt/local/lib/
-L/usr/local/lib/
-L./
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/zlib/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/xforms/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/x11/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/uuid/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/utmp/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/users/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/unzip/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/univint/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/tcl/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/syslog/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/symbolic/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/sqlite/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/sdl/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl-unicode/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl-objpas/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl-extra/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl-console/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rsvg/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/regexpr/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/pthreads/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/postgres/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/pcap/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/paszlib/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/pasjpeg/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/oracle/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/openssl/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/opengles/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/opengl/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/opencl/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/openal/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/odbc/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/odata/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/objcrtl/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/numlib/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/ncurses/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/mysql/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/libvlc/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/libtar/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/libpng/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/libgd/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/libcurl/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/lexyacc/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/iosxlocale/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/imlib/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/imagemagick/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/iconvenc/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/ibase/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/httpd24/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/httpd22/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/hermes/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/hash/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/gtk2/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/gtk1/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/graph/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/gnome1/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/gmp/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/gdbm/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fv/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fppkg/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fpmkunit/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fpindexer/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fpgtk/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fftw/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-xml/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-web/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-stl/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-sound/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-sdo/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-res/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-registry/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-process/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-pdf/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-passrc/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-net/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-json/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-js/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-image/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-fpcunit/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-extra/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-db/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-base/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-async/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fastcgi/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/dblib/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/cocoaint/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/chm/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/cairo/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/bzip2/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/bfd/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/aspell/
-L/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/
-L/usr/local/codetyphon/fpc/fpc32/bin/i386-darwin/
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/sysinit.o
/Users/rarnu/Code/Github/root-tools/native/lib/i386-darwin/cmd.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/system.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/lnfodwrf.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/exeinfo.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/objpas.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/strings.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/cthreads.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/classes.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/sysutils.o
/Users/rarnu/Code/Github/root-tools/native/lib/i386-darwin/JNI2.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/math.o
/Users/rarnu/Code/Github/root-tools/native/lib/i386-darwin/unt_ljava.o
/Users/rarnu/Code/Github/root-tools/native/lib/i386-darwin/unt_clean.o
/Users/rarnu/Code/Github/root-tools/native/lib/i386-darwin/unt_freeze.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/baseunix.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/unix.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/unixtype.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/initc.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/sysctl.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/unixutil.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/ctypes.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/types.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/typinfo.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/rtlconsts.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/errors.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/sysconst.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl-objpas/strutils.o
/Users/rarnu/Code/Github/root-tools/native/lib/i386-darwin/android.o
/Users/rarnu/Code/Github/root-tools/native/lib/i386-darwin/unt_cmd.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-process/process.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/fcl-process/pipes.o
/usr/local/codetyphon/fpc/fpc32/units/i386-darwin/rtl/termio.o
-lc
